export { default as GTab } from './src/Tab'
export { default as GTabContent } from './src/TabContent'
export { default as GTabs } from './src/Tabs'
export { default as GTabsHeader } from './src/TabsHeader'
export { default as GTabsBody } from './src/TabsBody'
